### ISSUE TITLE
VS Code extension crashes on Windows when the project is not on the C:\ drive

### ISSUE THREAD

**Issue by madcampos** [markuplint/markuplint#1806]
- Markuplint version: `4.7.1`
- Parser lang: Astro
- Node.js version: `20.13.0`
- OS: Windows 11

## Describe the bug

My project is in in a different drive than `C:\`, markuplint's server is crashing with the following error message:
```
2024-06-03 20:17:55.723 [info] Error: Parser module "p:\oss\blog\node_modules\@markuplint\astro-parser" is not found.
    at importParser (file:///c:/Users/madca/.vscode-insiders/extensions/yusukehirao.vscode-markuplint-4.7.1/node_modules/@markuplint/file-resolver/lib/resolve-parser.js:40:15)
    at async resolveParser (file:///c:/Users/madca/.vscode-insiders/extensions/yusukehirao.vscode-markuplint-4.7.1/node_modules/@markuplint/file-resolver/lib/resolve-parser.js:25:20)
    at async MLEngine.resolveParser (file:///c:/Users/madca/.vscode-insiders/extensions/yusukehirao.vscode-markuplint-4.7.1/node_modules/markuplint/lib/api/ml-engine.js:279:24)
    at async MLEngine.provide (file:///c:/Users/madca/.vscode-insiders/extensions/yusukehirao.vscode-markuplint-4.7.1/node_modules/markuplint/lib/api/ml-engine.js:205:52)
    at async MLEngine.setup (file:///c:/Users/madca/.vscode-insiders/extensions/yusukehirao.vscode-markuplint-4.7.1/node_modules/markuplint/lib/api/ml-engine.js:310:24)
    at async MLEngine.exec (file:///c:/Users/madca/.vscode-insiders/extensions/yusukehirao.vscode-markuplint-4.7.1/node_modules/markuplint/lib/api/ml-engine.js:72:22)
    at async MessagePort.<anonymous> (file:///c:/Users/madca/.vscode-insiders/extensions/yusukehirao.vscode-markuplint-4.7.1/node_modules/@markuplint/esm-adapter/esm/index.mjs:152:19)
```

Linting the project on the terminal works.

## Code Example or Playground URL

Here is the repo for the code: https://github.com/torontojs/blog

## Steps To Reproduce

1. Move project to another drive
2. Open the project on VS Code

## The current behavior

The extension crashes multiple times and VS Code shows a message saying it won't be started again.

## The expected behavior

The extension works on VS Code and don't throw an error.

**Comment by YusukeHirao** [comment]
@madcampos 

Thank you for reporting this issue.

I apologize for any inconvenience caused. Unfortunately, I'm not very familiar with the Windows environment, so my ability to directly resolve this is limited. However, I have marked this issue as "Pull Request Wanted" in hopes that someone with more expertise in Windows file systems can assist.

We appreciate your patience and any help from the community to address this problem.

Thank you for your understanding.
