### ISSUE TITLE
Error: Matching for a tree with var() is not supported

### ISSUE THREAD

**Issue by ZuBB** [markuplint/markuplint#1916]
Env: 

- Markuplint version: `4.9.2`
- Parser lang: @markuplint/nunjucks-parser@latest (as of today)
- Node.js version: `v20.12.2`
- OS: macOS

## Describe the bug
I am in the middle of implementing a new feature in my project and I noticed that I started to get this (new) error

```
<markuplint> error: Error: Matching for a tree with var() is not supported                                                                
    at matchSyntax (file:///Users/vv/work/career-partner/source-code/node_modules/css-tree/lib/lexer/Lexer.js:71:39)                      
    at Lexer.match (file:///Users/vv/work/career-partner/source-code/node_modules/css-tree/lib/lexer/Lexer.js:354:16)                     
    at cssSyntaxMatch (file:///Users/vv/work/career-partner/source-code/node_modules/@markuplint/types/lib/css-syntax.js:81:26)           
    at _checkKeywordType (file:///Users/vv/work/career-partner/source-code/node_modules/@markuplint/types/lib/keyword-type.js:46:40)      
    at checkKeywordType (file:///Users/vv/work/career-partner/source-code/node_modules/@markuplint/types/lib/keyword-type.js:17:20)       
    at check (file:///Users/vv/work/career-partner/source-code/node_modules/@markuplint/types/lib/check.js:9:16)                          
    at valueCheck (file:///Users/vv/work/career-partner/source-code/node_modules/@markuplint/rules/lib/attr-check.js:85:21)               
    at file:///Users/vv/work/career-partner/source-code/node_modules/@markuplint/rules/lib/attr-check.js:56:25                            
    at Array.map (<anonymous>)                                                                                                            
    at attrCheck (file:///Users/vv/work/career-partner/source-code/node_modules/@markuplint/rules/lib/attr-check.js:55:31) (@markuplint/ml
-core) /Users/vv/work/career-partner/source-code/prof_test/templates/includes/common-widgets/match-as-progress.html:0:0                   
```

The thing is, the subject file didn't get a lot of changes, and changes look trivial to me, but... or maybe I am just blind/tired

## Code Example or Playground URL

<details>
  <summary>Old version of file, no error</summary>
```html
{% spaceless %}
{% load i18n %}

{% comment %}

NOTE: income data
-----------------
$ring-size: 155;
$ring-thickness: 9;

NOTE: logic behind the math
---------------------------
Width of the stroke that goes along with circle "resides" on both parts of the
circle shape: 50% inside, 50% of outside. this is how default value of
"stroke-linejoin" prop works. Work of other values (only inside, only outside)
is not implemented in browsers yet. That is why we do this 9/2 tricks.

NOTE: math
-----------------
$svg-circle-radius: math.div(($ring-size - $ring-thickness), 2);  // 73
$svg-circle-centre-coord: $svg-circle-radius + math.div(9, 2);    // 77.5

NOTE: explanation
-----------------
* r/cx/cy have to be here (in HTML), as they are crutial for FF&SF
* applying those through CSS works only for Chrome

{% endcomment %}

<div class="match-as-progress position-relative w-100 h-100 text-center">
    {% with
        length="var(--circumference)"
        percent=matched_profession.match_percent
    %}
    <svg
        class="position-absolute top-0 start-0"
        preserveAspectRatio="xMidYMid meet"
        viewBox="0 0 155 155"
    >
        <circle r="73" cx="77.5" cy="77.5"></circle>
        <circle
            r="73" cx="77.5" cy="77.5"
            stroke="{% include "includes/results-widgets/fit-level-color.html" with
                fit_level=fit_level
            %}"
            style="stroke-dashoffset: calc(calc({{ length }} * (100 - {{ percent }}) / 100) * 1px)"
        ></circle>
    </svg>
    {% endwith %}

    <div class="match-label position-absolute w-100 text-body-tertiary">{% trans "Your match:" %}</div>
    <div class="match-value position-absolute w-100 fw-semibold">{{ matched_profession.match_percent }}%</div>
</div>
{% endspaceless %}
```  
</details>

<details>
  <summary>new version of the file. one that triggers an error</summary>
  
  ```html
{% spaceless %}
{% load i18n %}

{% comment %}

NOTE: income data
-----------------
$ring-size: 155;
$ring-thickness: 9;

NOTE: logic behind the math
---------------------------
Width of the stroke that goes along with circle "resides" on both parts of the
circle shape: 50% inside, 50% of outside. this is how default value of
"stroke-linejoin" prop works. Work of other values (only inside, only outside)
is not implemented in browsers yet. That is why we do this 9/2 tricks.

NOTE: math
-----------------
$svg-circle-radius: math.div(($ring-size - $ring-thickness), 2);  // 73
$svg-circle-centre-coord: $svg-circle-radius + math.div(9, 2);    // 77.5

NOTE: explanation
-----------------
* r/cx/cy have to be here (in HTML), as they are crutial for FF&SF
* applying those through CSS works only for Chrome

{% endcomment %}

<div class="match-as-progress position-relative w-100 h-100 text-center">
    <svg
        class="position-absolute top-0 start-0"
        preserveAspectRatio="xMidYMid meet"
        viewBox="0 0 155 155"
    >
        <circle r="73" cx="77.5" cy="77.5"></circle>
        <circle
            r="73" cx="77.5" cy="77.5"
            stroke="{% include "includes/results-widgets/fit-level-color.html" %}"
            style="stroke-dashoffset: calc(calc(var(--circumference) * (100 - var(--percent{{ forloop.counter|default:1 }})) / 100) * 1px)"
        ></circle>
    </svg>

    <div class="match-label position-absolute w-100 text-body-tertiary">{% trans "Your match:" %}</div>
    <div class="match-value position-absolute w-100 fw-semibold">{{ matched_profession.match_percent }}%</div>
</div>
{% endspaceless %}
  ```
</details>

## Steps To Reproduce

1. Just validate the attached file

## The current behavior
I am getting "_Matching for a tree with var() is not supported_" error

## The expected behavior
I would like to not get an error

**Comment by YusukeHirao** [comment]
@ZuBB 

Thank you for your report.
This is the same issue: https://github.com/markuplint/markuplint/issues/364

**Comment by ZuBB** [comment]
> @ZuBB
> 
> Thank you for your report. This is the same issue: #364

Okay, it seems svg has a few issues. Is there any way to entirely ignore the `<svg>` tag?

**Comment by YusukeHirao** [comment]
You can disable specific rules for elements using [`childNodeRules`](https://markuplint.dev/docs/configuration/properties#childnoderules) in your `.markuplintrc` file. Here's an example configuration:

```json
{
  "nodeRules": [
    {
      "selector": "svg",
      "inheritance": true,
      "rules": {
        "rule-name": false
      }
    }
  ]
}
```

However, there isn't a way to completely disable all rules for a tag because `nodeRules` uses a merging strategy.

**Comment by ZuBB** [comment]
it's sad because it seems I can't make any of these
* make `<svg>` totally ignored tag
* make all rules turned off for `svg` tag

And because the error I faced was not a failure of some rule but rather a JS error that had been successfully caught the most viable option for me right now is to return to the old version of the code..

**Comment by YusukeHirao** [comment]
I see. Well, in that case, it seems like I should catch that error exception and make sure the process continues. I'll give it a try.
